name: deployment-status
on:
  deployment_status:

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          echo ${{ github.event.deployment.id }}
          echo ${{ github.event.deployment.environment }}
          echo ${{ github.event.deployment.ref }}
          echo ${{ github.event.deployment.sha }}
          echo ${{ github.event.deployment_status.status }}
          