name: feature
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
  issue_comment:
    types: [created]      
jobs:
  build:
    # if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'running'
      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.1
        id: deployment
        with:
          step: start
          token: ${{ secrets.TOKEN }}
          ref: ${{ github.head_ref }}
          env: development